spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:192.168.247.12}:${MYSQL_PORT:3306}/ficus_virens?characterEncoding=utf8&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:yishuida}
  liquibase:
    enabled: true
    change-log: classpath:database/changelog/master.xml

logging:
  level:
    dev.daqiang.blog.infra.mapper: debug
    org:
      springframework: debug