spring:
  profiles:
    active: dev

mybatis:
  #check-config-location: false
  type-aliases-package: dev.daqiang.ficusvirens.root.domain.entity
  configuration:
    database-id: mysql
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath:mapper/*.xml

bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000