spring:
  profiles:
    active: dev


mybatis:
  check-config-location: false
  type-aliases-package: dev.daqiang.ficusvirens.root.domain.entity
  configuration:
    database-id: mysql

  mapper-locations: classpath:mapper/*.xml


