spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:PUBLIC;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  liquibase:
    enabled: true
    change-log: classpath:database/changelog/master.xml
  h2:
    console:
      enabled: true

logging:
  level:
    dev.daqiang.blog.infra.mapper: debug
