spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.247.11:3306/ficus_virens?characterEncoding=utf8&useSSL=false
    username: root
    password: yishuida
  liquibase:
    enabled: true
    change-log: classpath:database/changelog/master.xml

logging:
  level:
    dev.daqiang.blog.infra.mapper: debug

mybatis:
  check-config-location: false
  type-aliases-package: dev.daqiang.ficusvirens.root.domain.entity # 无效
  configuration:
    database-id: mysql
  mapper-locations: classpath:mapper/*.xml
